baseurl = "https://www.indalit.com/"
absurl = "https://www.indalit.com"
title = "Indalit Cloud Consulting"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

[languages.en]
[languages.es]

# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-114523366-1"

# Define the number of posts per page
paginate = 10
PaginatePath = "page"

[menu]

# Main menu

[[menu.main]]
    name = "home"
    url  = "/"
    weight = 1


[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 5

#[[menu.main]]
#    name = "FAQ"
#    identifier = "faq"
#    url  = "/faq/"
#    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

[[menu.main]]
    name  = "Packs"
    url  = "/packs/aws-consulting-services/"
    weight  = 2
    identifier = "packs"

[[menu.main]]
    name  = "AWS"
    url  = "/aws-amazon-web-services-consultants/"
    weight  = 3
    identifier = "aws"

#[[menu.main]]
#    name  = "DevOps"
#   url  = "/devops-consultants/"
#    weight  = 4
#    identifier = "devops"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/MoiCoquille"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/indalitcloud"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:info@indalit.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/indalit-cloud-consulting/"
    pre = "<i class='fa fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 5
    name = "Meetup"
    url = "https://www.meetup.com/AWS-Valencia/"
    pre = "<i class='fa fa-2x fa-meetup'></i>"

[params]
    viewMorePostLink = "/blog/"
#    author = "DevCows"
#    defaultKeywords = ["devows", "hugo", "go"]
#    defaultDescription = "Site template made by devcows using hugo"
	author = "Veronique Robitaille"
	defaultKeywords = ["AWS", "Amazon Web Services", "Consultant"]
	defaultDescription = "AWS Consultants & Project Managers"
    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCSC6pldLflbgRPnKU6ESAoUUyrAL51rKI"
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "red"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = ""

    about_us = "<p>We are a great team.  Our objective is to keep our people satisfied and well trained.  This way we work in a healthy positive environment with the elite of the sector.  Priority is on competence and knowledge.  We believe this is what makes the difference in the services we provide to our customers.</p>"
    copyright = "Copyright &#169 2018 - 2019, Indalit Cloud Consulting; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"

address = """<p><strong>Indalit Cloud Consulting</strong>
<br>Calle Reina Violante
<br>46015 Valencia
<strong>Spain</strong>
<br>
<br>+34 963 684 585
<br>
</p>
"""

    latitude = "39.484992999999996"
    longitude = "-0.402362900000071"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "The Founders"
    subtitle = "Both founders are highly skilled in their expertise with much experience in their field.  Together they make a winning team with what it takes to build a technical consulting company."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to know more?"
    subtitle = "Visit the rest of the site to get more in depth information on the subjects we've just barely touched."
    link_url = "/packs/"
    link_text = "More on the AWS Packages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Keeping up to date with the technologies and sharing this knowledge is important to us.  The open source model mindset applies perfectly to what we aim to be as a company.  To build you must actually do things, talk is simply not enough."
